### ISSUE TITLE
Missing ibssh-aerosol.so and error in munich-ssh

### ISSUE THREAD

**Issue by YingW1014** [cerea-lab/munich#1]
I am using munich-ssh on HPC. However, I can not find "ssh-aerosol/src/libssh-aerosol.so" in the MUNICH include folder after compilation. There is also an error called "Error on dlsym : munich-ssh: undefined symbol: api_sshaerosol_set_standalone_". What's the reason for this?

**Comment by YingW1014** [comment]
Problem solved

**Comment by flyingfishing** [comment]
How did you solve this problem?I encountered the same problem
